# Generated by Django 5.2.5 on 2025-09-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_done',
        ),
    ]
